/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
export {}
declare global {
  const Download: typeof import('../composables/useCommon')['Download']
  const dateFormat: typeof import('../composables/useCommon')['dateFormat']
  const deepClone: typeof import('../composables/useCommon')['deepClone']
  const del: typeof import('../composables/useRequest')['del']
  const get: typeof import('../composables/useRequest')['get']
  const getConfigCol: typeof import('../composables/useCommon')['getConfigCol']
  const post: typeof import('../composables/useRequest')['post']
  const put: typeof import('../composables/useRequest')['put']
  const removeAllPendingRequest: typeof import('../composables/useRequest')['removeAllPendingRequest']
  const removePendingRequest: typeof import('../composables/useRequest')['removePendingRequest']
}
